# Lista de Exercícios — Pandas

Nesta atividade, cada grupo utilizará um dataset diferente. As respostas devem ser obtidas utilizando a biblioteca Pandas.

In [1]:
print("Teste")

Teste

In [2]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\52625267\documents\github\fundamentosprogramacao\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\52625267\documents\github\fundamentosprogramacao\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.3 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp312-cp312-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\52625267\documents\github\fundamentosprogramacao\.venv\lib\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in c:\users\52625267\documents\github\fundamentosprogramacao\.venv\lib\site-packages (from matplotlib) (26.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.2.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\52625267\documents\github\fundamentosprogramacao\.venv\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\52625267\documents\github\fundamentosprogramacao\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.9-cp312-cp312-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.2 MB 3.4 MB/s eta 0:00:03
   ---------- ----------------------------- 2.1/8.2 MB 6.2 MB/s eta 0:00:01
   ------------ --------------------------- 2.6/8.2 MB 4.2 MB/s eta 0:00:02
   ------------ --------------------------- 2.6/8.2 MB 4.2 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.2 MB 3.1 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.2 MB 2.8 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.2 MB 2.8 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.2 MB 2.4 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.2 MB 2.2 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.2 MB 2.3 MB/s eta 0:00:02
   ------------------------ --------------- 5.0/8.2 MB 2.2 MB/s eta 0:00:02
   -------------------------- ------------- 5.5/8.2 MB 2.2 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.2 MB 2.2 MB/s eta 0:00:02
   ------------------------------- -------- 6.6/8.2 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.2 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.2 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 2.3 MB/s eta 0:00:00
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp312-cp312-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ----------------- ---------------------- 1.0/2.3 MB 10.1 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 5.1 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 3.5 MB/s eta 0:00:00
Downloading kiwisolver-1.5.0-cp312-cp312-win_amd64.whl (73 kB)
Downloading pillow-12.2.0-cp312-cp312-win_amd64.whl (7.1 MB)
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.8/7.1 MB 4.2 MB/s eta 0:00:02
   -------- ------------------------------- 1.6/7.1 MB 3.1 MB/s eta 0:00:02
   ---------- ----------------------------- 1.8/7.1 MB 2.7 MB/s eta 0:00:02
   -------------- ------------------------- 2.6/7.1 MB 2.7 MB/s eta 0:00:02
   -------------------- ------------------- 3.7/7.1 MB 3.2 MB/s eta 0:00:02
   ----------------------- ---------------- 4.2/7.1 MB 3.0 MB/s eta 0:00:01
   -------------------------- ------------- 4.7/7.1 MB 3.0 MB/s eta 0:00:01
   ----------------------------- ---------- 5.2/7.1 MB 2.9 MB/s eta 0:00:01
   -------------------------------- ------- 5.8/7.1 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 6.3/7.1 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.1 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 7.1/7.1 MB 2.8 MB/s eta 0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.10.9 pillow-12.2.0 pyparsing-3.3.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import pandas as pd
import matplotlib.pyplot as plt

# Carregue seu dataset abaixo
# Exemplo:
# df = pd.read_csv('dataset.csv')

df = pd.read_csv('heart_attack_dataset.csv')

df.head()

Matplotlib is building the font cache; this may take a moment.

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

## 1. Exploração Inicial

### Questão 1

Quantas linhas e colunas existem no dataset?

In [16]:
df.shape

(303, 14)

### Questão 2

Quais são os nomes das colunas?

In [17]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')

### Questão 3

Quais os tipos de dados presentes?

In [18]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

### Questão 4

Existem valores ausentes? Em quais colunas?

In [19]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

### Questão 5

Existem registros duplicados?

In [ ]:
não existem registros duplicados.

df.drop_duplicates

<bound method DataFrame.drop_duplicates of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]>

In [22]:
df.shape

(303, 14)

### Questão 6

Quantos valores únicos existem em uma coluna categórica?

In [23]:
df['sex'].unique()

array([1, 0])

### Questão 7

Qual coluna possui maior quantidade de valores distintos?

In [57]:
df.target

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

### Questão 8

Mostre uma amostra aleatória do dataset.

In [24]:
df.sample()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
103,42,1,2,120,240,1,1,194,0,0.8,0,0,3,1

## 2. Seleção e Filtragem

### Questão 1

Filtre registros com valores acima da média em uma coluna numérica.

In [25]:
df['age'].mean()

np.float64(54.366336633663366)

In [26]:
df[df['age'] > 54]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

### Questão 2

Filtre registros pertencentes a uma categoria específica.

In [28]:
df['age']

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

### Questão 3

Filtre registros com múltiplas condições.

In [53]:
df[(df['age'] > 54) & (df['sex'] < 1)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2,1
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2,1
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1
38,65,0,2,155,269,0,1,148,0,0.8,2,0,2,1
39,65,0,2,160,360,0,0,151,0,0.8,2,0,2,1
54,63,0,2,135,252,0,0,172,0,0.0,2,0,2,1
59,57,0,0,128,303,0,0,159,0,0.0,2,1,2,1
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
69,62,0,0,124,209,0,1,163,0,0.0,2,0,2,1
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2,1
82,60,0,2,102,318,0,1,160,0,0.0,2,1,2,1
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1
89,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2,1
105,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1
110,64,0,0,180,325,0,1,154,1,0.0,2,0,2,1
112,64,0,2,140,313,0,1,133,0,0.2,2,0,3,1
120,64,0,0,130,303,0,1,122,0,2.0,1,2,2,1
127,67,0,2,152,277,0,1,172,0,0.0,2,1,2,1
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
136,60,0,2,120,178,1,1,96,0,0.0,2,0,2,1
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
147,60,0,3,150,240,0,1,171,0,0.9,2,0,2,1
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1
153,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1
155,58,0,0,130,197,0,1,131,0,0.6,1,0,2,1
161,55,0,1,132,342,0,1,166,0,1.2,2,0,2,1
167,62,0,0,140,268,0,0,160,0,3.6,0,2,2,0
181,65,0,0,150,225,0,0,114,0,1.0,1,3,3,0
182,61,0,0,130,330,0,0,169,0,0.0,2,0,2,0
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0
207,60,0,0,150,258,0,0,157,0,2.6,1,2,3,0
213,61,0,0,145,307,0,0,146,1,1.0,1,0,3,0
216,62,0,2,130,263,0,1,97,0,1.2,1,1,3,0
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0
223,56,0,0,200,288,1,0,133,1,4.0,0,2,3,0
241,59,0,0,174,249,0,1,143,1,0.0,1,0,2,0
246,56,0,0,134,409,0,0,150,1,1.9,1,2,3,0
252,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
258,62,0,0,150,244,0,1,154,1,1.4,1,0,2,0
260,66,0,0,178,228,1,1,165,1,1.0,1,2,3,0
263,63,0,0,108,269,0,1,169,1,1.8,1,2,2,0
266,55,0,0,180,327,0,2,117,1,3.4,1,0,2,0
278,58,0,1,136,319,1,0,152,0,0.0,2,2,2,0
289,55,0,0,128,205,0,2,130,1,2.0,1,1,3,0
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1,0
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

### Questão 4

Filtre registros contendo valores nulos.

In [ ]:
não existem valores nulos.

AttributeError: 'function' object has no attribute 'sum'

### Questão 5

Filtre registros dentro de um intervalo de valores.

In [56]:
df[(df['age'] > 54) & (df['age'] < 60)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1,0
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1,0
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

## 3. Estatística Descritiva

### Questão 1

Calcule média, mediana, mínimo, máximo e desvio padrão.

In [58]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

### Questão 2

Identifique os registros acima da média.

In [62]:
df.mean['mean']

TypeError: 'method' object is not subscriptable

### Questão 3

Identifique os registros abaixo da mediana.

### Questão 4

Qual coluna numérica possui maior variabilidade?

In [ ]:
# Sua resposta aqui

## 4. Ordenação

### Questão 1

Ordene o dataset de forma crescente.

In [81]:
df.sort_values

<bound method DataFrame.sort_values of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal  target
0        0   0     1       1
1        0   0     2       1
2        2   0     2       1
3        2   0     2       1
4        2   0     2       1
..     ...  ..   ...     ...
298      1   0     3       0
299      1   0     3       0
300      1   2     3       0
301      1   1     3       0
302      1   1     2       0

[303 rows x 14 columns]>

### Questão 2

Ordene o dataset de forma decrescente.

In [82]:
df.sort_values(ascending=False)

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

### Questão 3

Mostre os 5 maiores registros.

In [78]:
dfmax = df.max()

In [79]:
dfmax.head()

age          77.0
sex           1.0
cp            3.0
trestbps    200.0
chol        564.0
dtype: float64

### Questão 4

Mostre os 5 menores registros.

In [75]:
dfmin = df.min()

In [76]:
dfmin.head()

age          29.0
sex           0.0
cp            0.0
trestbps     94.0
chol        126.0
dtype: float64

### Questão 5

Ordene utilizando múltiplas colunas.

In [ ]:
# Sua resposta aqui

## 6. Tratamento de Dados

### Questão 1

Identifique valores ausentes.

In [ ]:
# Sua resposta aqui

### Questão 4

Renomeie colunas.

In [ ]:
# Sua resposta aqui

### Questão 5

Crie uma nova coluna baseada em operações matemáticas.

In [ ]:
# Sua resposta aqui

## 9. Visualização de Dados

### Questão 1

Crie um gráfico de barras.

In [ ]:
# Sua resposta aqui

### Questão 2

Crie um histograma.

In [ ]:
# Sua resposta aqui

### Questão 3

Crie um gráfico de dispersão.

In [ ]:
# Sua resposta aqui

### Questão 4

Crie um boxplot.

In [ ]:
# Sua resposta aqui

### Questão 5

Escolha o gráfico mais adequado para representar os dados.

In [ ]:
# Sua resposta aqui